### ISSUE TITLE
LoadError: /lib/x86_64-linux-gnu/libc.so: invalid ELF header

### ISSUE THREAD

**Issue by stephenarifin-payscore** [IAPark/tiktoken_ruby#12]
I'm receiving the following error when I'm loading this gem in Github Actions, with the `ubuntu-latest` image. Any ideas?

```
LoadError: /lib/x86_64-linux-gnu/libc.so: invalid ELF header - /home/runner/work/payscore/payscore/payscore/vendor/ruby/3.0.0/gems/tiktoken_ruby-0.0.5-x86_64-linux-musl/lib/tiktoken_ruby/3.0/tiktoken_ruby.so
/home/runner/work/payscore/payscore/payscore/vendor/ruby/3.0.0/gems/tiktoken_ruby-0.0.5-x86_64-linux-musl/lib/tiktoken_ruby.rb:8:in `require_relative'
/home/runner/work/payscore/payscore/payscore/vendor/ruby/3.0.0/gems/tiktoken_ruby-0.0.5-x86_64-linux-musl/lib/tiktoken_ruby.rb:8:in `<top (required)>'
/home/runner/work/payscore/payscore/payscore/config/application.rb:7:in `<top (required)>'
/home/runner/work/payscore/payscore/payscore/Rakefile:4:in `require_relative'
/home/runner/work/payscore/payscore/payscore/Rakefile:4:in `<top (required)>'
/home/runner/work/payscore/payscore/payscore/vendor/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/runner/work/payscore/payscore/payscore/vendor/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/runner/work/payscore/payscore/payscore/vendor/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:50:in `invoke'
/home/runner/work/payscore/payscore/payscore/vendor/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by gjtorikian** [comment]
I reckon this has been resolved as it hasn't come up in a while. Feel free to reopen if I'm mistaken.
